const Map<String, String> en = {
  'waiting': 'Please wait!',
  // login
  "login": 'Login',
  'login_by_indentifier': 'Login by ID',
  'forgot_identifier': 'Forget ID?',
  'invalid_account': 'ID is not correct. Please try again!',
  'enter_id': 'Please enter ID to login!',
  'forgot_password': 'Forgot Password?',
  'register' : 'Register account',

  //forgot identifier
  'phone_number' : 'Phone Number',
  'send' : 'Send',
  'send_otp_phone' : 'OTP code will be sent to your phone number',
  'enter_new_login_id' : 'Enter New Login ID',
  'new_login_id' : 'New Login ID',
  're_enter_login_id' : 'Re-enter ID code',

  //register
  'full_name' : 'Full Name',
  'user_name' : 'User Name',
  'password' : 'Password',
  'confirm_password' : 'Confirm Password',
  'name_parents' : 'Parents name',
  'gmail_address' : 'Gmail',
  'sex' : 'Sex',
  'disability' : 'Disability',
  'provinces' : 'Provinces(*)',
  'wards' : 'Wards(*)',
  'address' : 'House number/lane/alley(*)',
  'login_id' : 'Login id',
  'note_register' : 'Note: This ID will be used to log in when entering the application\nExample: Nguyen The Ngoc - ngocntph123',
  'male' : 'Male',
  'female' : 'Female',
  'other' : 'Other',
  'yes' : 'Yes',
  'no' : 'No',
  'otp_send' : 'OTP has been sent',
  'not_receive_otp' : 'You have not received the otp code?',
  're_send': 'ReSend',
  're_send_otp_later': 'Resend OTP later',
  // validate form register
  'please_enter_phone_number' : 'Please enter phone number',
  'invalid_phone_number' : 'Invalid phone number',
  'please_enter_name_parents' : 'Please enter parents name',
  'please_enter_gmail' : 'Please enter gmail',
  'gmail_invalid' : 'Gmail is invalid',
  'please_enter_sex' : 'Please choose sex',
  'please_enter_login_id' : 'Please enter login id',
  'login_id_invalid' : 'Login id is invalid',
  'please_enter_disability' : 'Please choose disability',
  'please_enter_provinces' : 'Please choose provinces',
  'please_enter_wards' : 'Please choose wards',
  'please_enter_address' : 'Please enter address',

  // add child
  'sunday': 'Sunday',
  'monday': 'Monday',
  'tuesday': 'Tuesday',
  'wednesday': 'Wednesday',
  'thursday': 'Thursday',
  'friday': 'Friday',
  'saturday': 'Saturday',
  'choose_date_of_birth' : 'Choose date of birth',
  'date_of_birth' : 'Date of birth',
  'child_name_add' : 'Child\'s name (nickname)',
  'school_add' : 'School',
  'grade_add' : 'Grade',
  'class_add' : 'Class',
  'my_dear_child' : 'My dear child',
  'add' : 'Add',

  //validate add child

  'please_enter_child_name' : 'Please enter child name',
  'please_enter_school' : 'Please choose school',
  'please_enter_grade' : 'Please choose grade',
  'please_enter_class' : 'Please choose class',

  //profile
  'update' : 'Update',
  'delete_account' : 'Delete Account',
  'update_profile' : 'Update Profile',
  'note_profile' : 'Note: Phone numbers will be updated separately to protect user information.',
  'confirm_delete_account' : 'After deleting,you will not be able to access this account.\n\nAre you sure you want to delete this account?',
  'new_phone_number' : 'New phone number',

  //home
  'create_account' : 'Create child account',

  //My library
  'grade_1' : 'Grade 1',
  'grade_2' : 'Grade 2',
  'grade_3' : 'Grade 3',
  'grade_4' : 'Grade 4',
  'grade_5' : 'Grade 5',

  // declare_parent_code
  'save_safety_code' : 'Save safety code',
  'parent_setup': 'Parent setup safety code',
  're_parent_setup': 'Re-enter safety code',
  'illegal_code': 'Safety code is not correct. Please try again!',
  // validate_code
  'enter_parent_code': 'Parent enter safety code',
  'parent_code_correct': 'Safety code is correct',
  'parent_code_incorrect': 'Safety code is incorrect!',
  'config_parent_code': 'Please setup safety code first!',
  // kit_space
  'world_of': 'Reading space',
  'area_of_parent': 'Parent space',
  'report': 'Report',
  'library': 'Library',
  'guideline_internet': 'Internet safety\nguideline',
  'personal_info': 'Personal Info',
  'settings': 'Settings',
  'add_child_account' : 'Add child\naccount',
  'settings_and_management': 'Settings \n & Management',
  'app_info': 'App Info',
  'report_personal_info': 'Personal\ninfo',
  'select_account_remind': 'Please choose your account and start',
  'reading': 'Reading',
  'e_book': 'E-Book',
  'share' : 'Share',


  // safety
  'hello': "Hello ",
  'safety_1': 'I am LoLo, let\'s study together within\n',
  'app_name': 'Vui đọc cùng em',
  'nhe': '!',
  'safety_2': 'To get started, watch a clip of the\n',
  'safety_3': 'Children\'s Online Safety Guide.',
  'title_video_safety': 'Children\'s Online Safety Guide',
  'sub_video_safety': 'Let\'s finish the Survey to enter reading world',
  'safety_finish_1': 'You guys have finished watching the guide.',
  'safety_finish_2': 'Now let\'s take a survey  and see if you\'re ready',
  'safety_finish_3': 'to explore the app!',
  'safety_finish_warning_1': 'Note: Children need adult supervision',
  'safety_finish_warning_2': 'when performing this activity.',
  'safety_survey_title': 'Online safety guide for children',
  're_view_safety_video': 'Watch again',
  'safety_survey_4': 'SORRY! You got only @numOfQuiz correct questions',
  'safety_survey_5': 'Please review video and take the quiz again!',
  'safety_survey_6': 'GREAT! You got @numOfQuiz correct questions',
  'safety_survey_7': 'Congratulations on passing the survey',
  'safety_survey_8': 'Now welcome to ',
  'safety_survey_9': 'SORRY! Your answer is not correct',
  'safety_survey_10': 'GREAT! You got the correct answer!',
  'quiz': 'Quiz',
  // grade
  'grade': 'Grade @grade',
  'my_library': 'My library',
  'my_e_library': 'My library',
  'lesson': 'Lesson',
  'topic': 'Topic',
  'star': 'Star',
  'my_progess': 'Learning journey',
  'is_updating': 'Feature is updating!',
  'change_acc': 'Change account',
  'book_number': 'Number of books',
  // star board
  'let_coloring': 'Let\'s choose to color and fill in the picture',
  'star_board_title': 'Star board',
  'star_total': "Total: ",
  'week': 'Week@week',
  'month': 'Month',
  'year': 'Year',
  'this_week': 'This week',
  'this_month': 'This month',
  'this_year': 'This year',
  'last_week': 'Last week',
  'last_month': 'Last month',
  'last_year': 'Last year',
  'num_of_star': '@stars Star',
  'num_of_year': 'Year @year',
  'num_of_lesson_learned': 'Lesson learnt',
  'average_time_per_day': 'Time per day',
  'total_time': 'Total time',

  // management space
  'day': 'days',
  'minute': 'minutes',
  'hour': 'hours',
  'second': 'seconds',
  'parent_info': 'Parent info',
  'parent_name': 'Parent name',
  'parent_phone': 'Phone number',
  'child_info': 'Child info',
  'child_name': 'Child name@string',
  'child_identifier': 'Child ID@string',
  'class': 'Class@string',
  'school': 'School@string',
  'enthnic': 'Enthnic@string',
  'ward': 'Ward@string',
  'district': 'District@string',
  'app_created_by': 'App developed by Vietnamese',
  'other_info': 'Other info@string',
  'language': 'Language',
  'volume': 'Volume',
  'safety_code': 'Safety code',
  'en_language': 'English',
  'vi_language': 'Vietnamese',
  "on": 'On',
  "off": 'Off',
  'old_safety_code': 'Enter old code',
  'new_safety_code': 'Enter new code',
  're_new_safety_code': 'Re-enter new code',
  // api
  'connection_failed': 'Disconected, please try again in a few minutes',
  'require_network_to_change_child':
      'You need an internet connection to change account!',
  'require_network_to_grade': 'You need an internet connection to enter Grade!',
  'require_network_to_topic':
      'You need an internet connection to access topic!',
  'error_handle': 'Error occured. Please try again later!',
  'download_success': 'Lesson downloaded. Now you can access freely!',
  'download_failed': 'Download failed. Please try again later!',
  // plugin
  'timeout_video_initialize': 'Error uploading video, Please try again later!',
  // game
  'save_success': 'Saved successfully',
  'lock_lesson': 'You have!',
  'error_try_again':
      'Error occured. Please try again when internet is available!',
  'update_success': 'Updated successfully!',
  'update_failed': 'Updated unsuccessfully!',
  'require_network': 'This feature require internet!',
  'upload_avatar': 'Upload image',
  'safety_code_mismatched': 'Safety code mismatched!',
  'unsuccess_safety_code': 'Safety code incorrect!',
  'updated_safety_code': 'Safety code updated!',
  'safety_code_not_enough': 'Please enter safety code!',
  'logout': 'Log out',
  'rest': 'Take rest',
  'continue': 'Continue',
  'expired_time_1': 'Today you\'ve spent',
  'expired_time_2': ' in app.\nLet\'s take some time for yourself and rest.',

  // question
  'note': 'Note',
  'let_do_it': 'Answer should not be blank!',
  'not_exactly': 'Incorrect',
  'exactly': 'Correct',
  'let_retry': 'Let\'s try again!',
  'continue_develop': 'Excellent, keep this spirit!',
  'retry': 'Retake',
  'next': 'Next',
  'phone': 'Phone',
  'confirm': 'Confirm',
  'start': 'Start',
  'watch_again': 'Watch again',
  'submit': 'Submit',
  'do_work': 'Do',
  'watch_clip': 'Watch',
  'hi': 'Hi',
  // calendar
  't2': 'Mon',
  't3': 'Tue',
  't4': 'Wed',
  't5': 'Thu',
  't6': 'Fri',
  't7': 'Sat',
  'cn': 'Sun',
  'w1': 'Week 1',
  'w2': 'Week 2',
  'w3': 'Week 3',
  'w4': 'Week 4',
  'th1': 'Jan',
  'th2': 'Feb',
  'th3': 'Mar',
  'th4': 'Apr',
  'th5': 'May',
  'th6': 'Jun',
  'th7': 'Jul',
  'th8': 'Aug',
  'th9': 'Sep',
  'th10': 'Oct',
  'th11': 'Nov',
  'th12': 'Dec',
  'm': 'p\'',
  //
  'cancel': 'Cancel',
  'right': 'Right',
  'wrong': 'Wrong',
  'dont_know': 'Do not know',
  'enter': 'Enter',
  'reply': 'Answer',
  'sending': "Sending",
  'question': 'Question',
  //
  'sesion_expired': 'Session expired. Please log in again!',

  //delete and download
  'delete_1': "After deleting the lessons, you will need to download again.",
  'delete_2': "\n Are you sure ?",
  'delete_3': "Deleted",
  'delete_4': "Deleting",
  'download_1':
      "Downloading many lessons can consume a lot of data.\nPlease make sure you are using Wi-Fi.",
  'download_2': "\n Are you sure ?",
  'download_3': "Completed",
  'download': 'Download',
  'delete': 'Delete',
  'delete_all': 'Delete All',
  'downloaded': 'Downloaded',
  'select_all': 'Select All',
  'deselect_all': 'Deselect all',
  'vietnamese': 'Vietnamese',
  'Hmong': 'Hmong',
  'library_title': 'ELibrary',
  'apply': 'Apply',
  'language_downloading': 'Downloading Language',
  'language_download_done': 'Download Language Successfully',
  'languague_download_error_1':
      'This language of the reading has been downloaded',
  'languague_download_error_2': 'Please select a language to download',
  'select_language': "Select language to download:",
  'default': 'Default',
  'back': 'Back',
// feedback
  "feedback_reading": "Reading Feedback",
  "evaluate_feedback_reading": "Evaluate / Reading Feedback",
  "you_want": "You want",
  "add_feedback": "Add feedback",
  "view_list_feedback": "View feedback list",
  "select_placeholder_class": "Class",
  "satisfaction_level": "Your satisfaction level\nwith this reading is",
  "want_comment_on": "You want to add feedback on",
  "select_placeholder_category": "General content",
  "enter_comment_hint": "Enter your feedback",
  "send_feedback": "Submit feedback",
  "plase_choose_feedback": "Please choose",
  "need_feedback": "needs feedback",
  "category": "Category",
  "content": "Content",
  "and": "and",
  "add_feedback_success": "Feedback added",
  "choose_class": "class",
  "all": "All",
  "important": "Important",
  "star_feedback": "Star",
  "classify": "Classify",
  "please_choose_class_view_feedback":
      "Please choose a class\nand a reading to view feedback",
  "data_empty": "No data available",
  "before": "before",
  "hide_feedback": "Hide feedback",
  "reply_feedback": "Reply to feedback",
  "comment_required": "Enter reply, please",
  "title_feedback_form": "Select the reading you want to comment on",
  "notification": "Notifications",
  "message": "Messages",
  "feedback": "Feedbacks",
  "guide_application": "Application\nUser Guide",
  "guide_application2": "Application User Guide",
  "feedback_content": "Comment content",
  "newest": "Newest",
  "oldest": "Oldest",
  "favorite": "Favorite",
  "most_reply": "Most reply",
  "notification_setting": "Notification Settings",
  "notification_enable": "Receive notifications for new messages",
  "notification_audio_enable": "Notification sound settings",
  "notification_sound_setting": "Notification ringtone volume",
  "btvn": "Homework",
  "reading_process": "Reading Progress",
  "interact": "Interaction",
  "group_setting": "Group Settings",
  "group_out": "Leave Group",
  "group_out_confirm": "Are you sure you want to leave the group?",
  "message_setting": "Message Settings",
  "group_uploaded": "Group avatar updated",
  "enter_answer": "Enter answer",
  "answer_question": "Answer the question",
};
