const Map<String, String> vi = {
  'waiting': 'Vui lòng đợi!',
  // login
  "login": 'Đăng nhập',
  'login_by_indentifier': 'Đăng nhập bằng ID',
  'forgot_identifier': 'Quên mã ID?',
  'invalid_account': 'ID chưa chính xác, vui lòng thử lại!',
  'enter_id': 'Vui lòng nhập ID để truy cập',
  'forgot_password': 'Quên mật khẩu?',
  'register': 'Tạo tài khoản',
  //forgot identifier
  'phone_number' : 'Số điện thoại',
  'send' : 'Gửi',
  'send_otp_phone' : 'Mã OTP sẽ được gửi về số điện thoại của bạn',
  'enter_new_login_id' : 'Nhập mã ID mới',
  'new_login_id' : 'MÃ ID MỚI',
  're_enter_login_id' : 'Nhập lại mã ID',

  //register
  'full_name' : 'Họ và tên',
  'user_name' : 'Tên tài khoản',
  'password' : 'Mật khẩu',
  'confirm_password' : 'Nhập lại mật khẩu',
  'name_parents' : 'Tên cha mẹ',
  'gmail_address' : 'Gmail',
  'sex' : 'Giới tính',
  'disability' : 'Tình trạng khuyết tật',
  'provinces' : 'Tỉnh/Thành Phố(*)',
  'wards' : 'Xã/Phường(*)',
  'address' : 'Số nhà/Ngõ/Ngách(*)',
  'login_id' : 'Id Đăng Nhập',
  'note_register' : 'Lưu ý: Id này sẽ dùng để đăng nhập khi vào ứng dụng\nVí dụ: Nguyễn Thế Ngọc - ngocntph123',
  'male' : 'Nam',
  'female' : 'Nữ',
  'other' : 'Khác',
  'yes' : 'Có',
  'no' : 'Không',
  'otp_send' : 'OTP đã được gửi đến',
  'not_receive_otp' : 'Bạn chưa nhận nhận được mã OTP?',
  're_send': 'Gửi lại',
  're_send_otp_later' : 'Gửi lại OTP sau',

  // validate form register
  'please_enter_phone_number' : 'Vui lòng nhập số điện thoại',
  'invalid_phone_number' : 'Số điện thoại không hợp lệ',
  'please_enter_name_parents' : 'Vui lòng nhập tên cha mẹ',
  'please_enter_gmail' : 'Vui lòng nhập gmail',
  'gmail_invalid' : 'Gmail không đúng định dạng',
  'please_enter_sex' : 'Vui lòng chọn giới tính',
  'please_enter_login_id' : 'Vui lòng nhập Id login',
  'login_id_invalid' : 'Id login không hợp lệ',
  'please_enter_disability' : 'Vui lòng xác nhận tình trạng khuyết tật',
  'please_enter_provinces' : 'Vui lòng chọn tỉnh/thành phố',
  'please_enter_wards' : 'Vui lòng chọn xã/phường',
  'please_enter_address' : 'Vui lòng nhập địa chỉ',


  // add child
  'sunday': 'Chủ nhật',
  'monday': 'Thứ hai',
  'tuesday': 'Thứ ba',
  'wednesday': 'Thứ tư',
  'thursday': 'Thứ năm',
  'friday': 'Thứ sáu',
  'saturday': 'Thứ bảy',
  'choose_date_of_birth' : 'Chọn ngày sinh',
  'date_of_birth' : 'Ngày sinh',
  'child_name_add' : 'Tên con (biệt danh)',
  'school_add' : 'Trường học',
  'grade_add' : 'Khối',
  'class_add' : 'Lớp',
  'my_dear_child' : 'Con yêu của ba mẹ',
  'add' : 'Thêm',

  //validate add child

  'please_enter_child_name' : 'Vui lòng nhập tên con',
  'please_enter_school' : 'Vui lòng chọn trường học',
  'please_enter_grade' : 'Vui lòng chọn khối',
  'please_enter_class' : 'Vui lòng chọn lớp',

  //profile
  'update' : 'Cập nhật',
  'delete_account' : 'Xóa tài khoản',
  'update_profile' : 'Cập nhật thông tin',
  'note_profile' : 'Lưu ý: Số điện thoại sẽ cập nhật riêng để bảo mật thông tin cho người dùng',
  'confirm_delete_account' : 'Sau khi thực hiện thao tác xóa,'
  ' bạn sẽ không thể truy cập tài khoản này.\n\nBạn có chắc chắn muốn xóa tài khoản này không?',
  'new_phone_number' : 'Số điện thoại mới',

  //home
  'create_account' : 'Tạo tài khoản con',


  //My library
  'grade_1' : 'Lớp 1',
  'grade_2' : 'Lớp 2',
  'grade_3' : 'Lớp 3',
  'grade_4' : 'Lớp 4',
  'grade_5' : 'Lớp 5',

  // declare_parent_code
  'save_safety_code' : 'Lưu mật khẩu',
  'parent_setup': 'Ba mẹ cài đặt mã an toàn',
  're_parent_setup': 'Xác nhận lại mã an toàn',
  'illegal_code': 'Mã an toàn chưa hợp lệ. Vui lòng thử lại!',
  // validate_code
  'enter_parent_code': 'Ba mẹ nhập mã số an toàn',
  'parent_code_correct': 'Mã an toàn hợp lệ',
  'parent_code_incorrect': 'Mã an toàn không hợp lệ!',
  'config_parent_code': 'Vui lòng thiết lập mã an toàn!',
  // kit_space
  'world_of': 'Khu vực của em',
  'area_of_parent': 'Khu vực của ba mẹ',
  'report': 'Báo cáo',
  'library': 'Thư viện',
  'guideline_internet': 'HDSD\nInternet an toàn',
  'personal_info': 'Thông tin\ncá nhân',
  'settings': 'Cài đặt',
  'settings_and_management': 'Quản lý \n & cài đặt',
  'add_child_account' : 'Thêm tài\nkhoản con',
  'app_info': 'Giới thiệu\nứng dụng',
  'report_personal_info': 'Thông tin\ncá nhân',
  'select_account_remind': 'Hãy chọn tài khoản của em và nhấn bắt đầu',
  'reading': 'Bài đọc',
  'e_book': 'Sách điện tử',
  'share' : 'Chia sẻ',

  // safety
  'hello': "Chào ",
  'safety_1': 'Tớ là Lô Lô, hãy cùng nhau học tập\nvới ứng dụng ',
  'app_name': 'Vui đọc cùng em',
  'nhe': ' nhé!',
  'safety_2': 'Để bắt đầu, chúng ta hãy cùng theo dõi\n',
  'safety_3': 'Hướng dẫn an toàn trên mạng cho trẻ.',
  'title_video_safety': 'Hướng dẫn về an toàn trên mạng cho trẻ',
  'sub_video_safety': 'Em hãy nhấn "TIẾP TỤC" sau khi xem xong hướng dẫn',
  'safety_finish_1':
      'Vậy là em đã theo dõi xong toàn bộ hướng dẫn an toàn mạng.',
  'safety_finish_2': 'Hãy cùng làm một bài khảo sát nhỏ',
  'safety_finish_3': 'để xem em đã sẵn sàng khám phá ứng dụng chưa nhé!',
  'safety_finish_warning_1': 'Lưu ý: Trẻ em cần có sự hỗ trợ của người lớn',
  'safety_finish_warning_2': 'khi thực hiện hoạt động này',
  'safety_survey_title': 'Khảo sát về an toàn trên mạng cho trẻ em',
  're_view_safety_video': 'Xem lại video',
  'safety_survey_4': 'THẬT TIẾC! Em mới trả lời đúng @numOfQuiz câu',
  'safety_survey_5':
      'Em hãy xem lại hướng dẫn và\nthử trả lời khảo sát một lần nữa nhé!',
  'safety_survey_6': 'THẬT TUYỆT! Em đã trả lời đúng @numOfQuiz câu',
  'safety_survey_7': 'Chúc mừng em đã hoàn thành khảo sát',
  'safety_survey_8': 'để truy cập ứng dụng ',
  'safety_survey_9': 'THẬT TIẾC! Trả lời sai mất rồi!',
  'safety_survey_10': 'THẬT TUYỆT! Em trả lời đúng rồi!',
  'quiz': 'Câu',
  // grade
  'grade': 'Lớp @grade',
  'my_library': 'Thư viện diệu kỳ',
  'my_e_library': 'Sách điện tử',
  'lesson': 'Bài học',
  'topic': 'Chủ đề',
  'star': 'Ngôi sao',
  'my_progess': 'Hành trình khám phá',
  'is_updating': 'Tính năng đang được cập nhật!',
  'change_acc': 'Thay đổi tài khoản',
  'book_number': 'Số lượng sách',
  // star board
  'let_coloring': 'Em hãy chọn màu và tô vào hình nhé',
  'star_board_title': 'Bảng sao vàng',
  'star_total': "Tổng: ",
  'week': 'Tuần@week',
  'month': 'Tháng',
  'year': 'Năm',
  'this_week': 'Tuần này',
  'this_month': 'Tháng này',
  'this_year': 'Năm này',
  'last_week': 'Tuần trước',
  'last_month': 'Tháng trước',
  'last_year': 'Năm trước',
  'num_of_star': '@stars Ngôi sao',
  'num_of_year': 'Năm @year',
  'num_of_lesson_learned': 'Tổng số bài đã đọc',
  'average_time_per_day': 'Thời gian trung bình/ngày',
  'total_time': 'Tổng thời gian',

  // management space
  'day': 'ngày',
  'minute': 'phút',
  'hour': 'giờ',
  'second': 'giây',
  'parent_info': 'Thông tin ba mẹ',
  'parent_name': 'Họ và tên',
  'parent_phone': 'Số điện thoại',
  'child_info': 'Thông tin của trẻ',
  'child_name': 'Họ và tên con@string',
  'child_identifier': 'Mã định danh@string',
  'class': 'Khối@string',
  'school': 'Trường@string',
  'enthnic': 'Dân tộc@string',
  'ward': 'Phường/xã@string',
  'district': 'Quận/huyện@string',
  'app_created_by': 'Ứng dụng được xây dựng bởi SC Việt Nam',
  'other_info': 'Các thông tin khác@string',
  'language': 'Ngôn ngữ',
  'volume': 'Âm lượng',
  'safety_code': 'Mã an toàn',
  'en_language': 'Tiếng Anh',
  'vi_language': 'Tiếng Việt',
  "on": 'Bật',
  "off": 'Tắt',
  'old_safety_code': 'Xác nhận mã cũ',
  'new_safety_code': 'Nhập mã mới',
  're_new_safety_code': 'Xác nhận mã mới',
  // api
  'connection_failed': 'Kết nối không thành công, vui lòng thử lại sau ít phút',
  'require_network_to_change_child':
      'Để thay đổi tài khoản, bạn cần phải có kết nối internet!',
  'require_network_to_grade':
      'Để vào lớp học bạn cần phải có kết nối internet!',
  'require_network_to_elibrary':
      'Để vào sách điện tử bạn cần phải có kết nối internet!',

  'require_network_to_topic': 'Để vào chủ đề bạn cần phải có kết nối internet!',
  'error_handle': 'Có lỗi trong quá trình xử lý. Vui lòng thử lại sau!',
  'download_success':
      'Tải bài học thành công. Bạn đã có thể tham gia vào bài học rồi nhé!',
  'download_failed': 'Tải bài học thất bại. Vui lòng thử lại sau!',
  // plugin
  'timeout_video_initialize':
      'Có lỗi trong quá trình tải lên video, vui lòng thử lại sau!',
  // game
  'save_success': 'Lưu ảnh thành công',
  'lock_lesson': 'Em hãy hoàn thành bài đọc trước đó để vào bài mới nhé!',
  'error_try_again': 'Đã xảy ra lỗi, vui lòng thử lại khi có internet!',
  'update_success': 'Cập nhật thành công!',
  'update_failed': 'Cập nhật thất bại!',
  'require_network': 'Chức năng này yêu cầu internet',
  'upload_avatar': 'Tải ảnh lên',
  'safety_code_mismatched': 'Mã an toàn không khớp!',
  'unsuccess_safety_code': 'Mã an toàn không đúng!',
  'updated_safety_code': 'Đã cập nhật mã an toàn!',
  'safety_code_not_enough': 'Vui lòng nhập đầy đủ mã an toàn!',
  'logout': 'Đăng xuất',
  'rest': 'Nghỉ ngơi',
  'continue': 'Tiếp tục',
  'expired_time_1': 'Hôm nay em đã sử dụng ứng dụng',
  'expired_time_2': ' rồi.\nHãy dành một chút thời gian để nghỉ ngơi nhé.',

  // question
  'note': 'Lưu ý',
  'let_do_it': 'Em hãy chọn hoặc điền đáp án trước khi nhấn "trả lời"',
  'not_exactly': 'Chưa chính xác',
  'exactly': 'Chính xác',
  'let_retry': 'Em hãy thử lại nhé!',
  'continue_develop': 'Em hãy tiếp tục phát huy nhé!',
  'retry': 'Thử lại',
  'next': 'Đi tiếp',
  'phone': 'SĐT',
  'confirm': 'Xác nhận',
  'start': 'Bắt đầu',
  'watch_again': 'Xem lại',
  'submit': 'Trả lời',
  'do_work': 'Làm bài',
  'watch_clip': 'Xem video',
  'hi': 'Xin chào',
  // calendar
  't2': 'Thứ 2',
  't3': 'Thứ 3',
  't4': 'Thứ 4',
  't5': 'Thứ 5',
  't6': 'Thứ 6',
  't7': 'Thứ 7',
  'cn': 'CN',
  'w1': 'Tuần 1',
  'w2': 'Tuần 2',
  'w3': 'Tuần 3',
  'w4': 'Tuần 4',
  'th1': 'Tháng 1',
  'th2': 'Tháng 2',
  'th3': 'Tháng 3',
  'th4': 'Tháng 4',
  'th5': 'Tháng 5',
  'th6': 'Tháng 6',
  'th7': 'Tháng 7',
  'th8': 'Tháng 8',
  'th9': 'Tháng 9',
  'th10': 'Tháng 10',
  'th11': 'Tháng 11',
  'th12': 'Tháng 12',
  'm': 'p\'',
  //
  'cancel': 'Huỷ',
  'right': 'Đúng',
  'wrong': 'Sai',
  'dont_know': 'Không biết',
  'enter': 'Nhập',
  'reply': 'Trả lời',
  'sending': "Đang gửi",
  'question': 'Câu hỏi',
  //
  'sesion_expired': 'Tài khoản hết phiên đăng nhập. Vui lòng đăng nhập lại!',
  //delete and download
  'delete_1': "Sau khi xoá bài đọc, bạn sẽ cần tải lại để tiếp tục học.",
  'delete_2': "\nBạn có chắc chắn muốn xoá không ?",
  'delete_3': "Xoá bài đọc thành công",
  'delete_4': "Đang xoá bài đọc",
  'download_1':
      "Việc tải nhiều bài đọc có thể tốn nhiều dung lượng.\nHãy đảm bảo bạn đang sử dụng Wifi",
  'download_2': "\nBạn có chắc chắn muốn tải xuống không ?",
  'download_3': "Tải bài học thành công",
  'download': 'Tải xuống',
  'delete': 'Xoá',
  'delete_all': 'Xoá hết',
  'downloaded': 'Đã tải',
  'select_all': 'Chọn hết',
  'deselect_all': 'Bỏ chọn Hết',
  'vietnamese': 'Tiếng Việt',
  'Hmong': 'Tiếng Mông',
  'library_title': 'Lưu trữ bài đọc',
  'apply': 'Áp Dụng',
  'language_downloading': 'Đang tải xuống ngôn ngữ',
  'language_download_done': 'Tải xuống ngôn ngữ thành công',
  'languague_download_error_1': 'Ngôn ngữ này của bài đọc đã được tải xuống',
  'languague_download_error_2': 'Hãy chọn một ngôn ngữ để tải xuống',
  'select_language': "Chọn ngôn ngữ tải xuống:",
  'default': 'Mặc Định',
  'back': 'Trở về',
  // feedback
  "feedback_reading": "Góp ý bài đọc",
  "evaluate_feedback_reading": "Đánh giá / Góp ý bài đọc",
  "you_want": "Bạn muốn",
  "add_feedback": "Thêm góp ý",
  "view_list_feedback": "Xem danh sách góp ý",
  "select_placeholder_class": "Lớp",
  "satisfaction_level": "Mức độ hài lòng của bạn\nđối với bài đọc này là",
  "want_comment_on": "Bạn muốn thêm góp ý về",
  "select_placeholder_category": "Nội dung chung",
  "enter_comment_hint": "Nhập góp ý của bạn",
  "send_feedback": "Gửi góp ý",
  "plase_choose_feedback": "Bạn hãy lựa chọn",
  "need_feedback": "cần góp ý",
  "category": "Danh mục",
  "content": "Nội dung",
  "and": "và",
  "add_feedback_success": "Đã thêm góp ý",
  "choose_class": "Chọn lớp",
  "all": "Tất cả",
  "important": "Quan trọng",
  "star_feedback": "Sao",
  "classify": "Phân loại",
  "please_choose_class_view_feedback":
      "Vui lòng chọn lớp\nvà chọn bài đọc để xem các góp ý",
  "data_empty": "Dữ liệu trống",
  "before": "trước",
  "hide_feedback": "Ẩn phản hồi",
  "reply_feedback": "phản hồi",
  "comment_required": "Vui lòng nhập trả lời",
  "title_feedback_form": "Chọn bài đọc bạn muốn góp ý",
  "notification": "Thông báo",
  "message": "Tin nhắn",
  "feedback": "Góp ý",
  "guide_application": "HDSD\nứng dụng",
  "guide_application2": "HDSD ứng dụng",
  "feedback_content": "Nội dung góp ý",
  "newest": "Mới nhất",
  "oldest": "Cũ nhất",
  "favorite": "Được yêu thích",
  "most_reply": "Phản hồi nhiều nhất",
  "notification_setting": "Cài đặt thông báo",
  "notification_enable": "Nhận thông báo khi có tin nhắn",
  "notification_audio_enable": "Thiết lập âm thanh thông báo",
  "notification_sound_setting": "Âm lượng chuông thông báo",
  "btvn": "BTVN",
  "reading_process": "Tiến độ đọc",
  "interact": "Tương tác",
  "group_setting": "Cài đặt nhóm",
  "group_out": "Rời khỏi nhóm",
  "group_out_confirm": "Bạn chắc chắn muốn rời khỏi nhóm?",
  "message_setting": "Cài đặt tin nhắn",
  "group_uploaded": "Đã cập nhật ảnh nhóm",
  "enter_answer": "Nhập câu trả lời",
  "answer_question": "Trả lời câu hỏi",

  //Video
  "pause_video" : "Dừng",
  "next_video" : "Tiếp tục",
  "review_video" : "Phát lại"
};
