name: EngKid
description: A new Flutter project.
publish_to: "none"
version: 0.3.0+34

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^1.9.2
  get: ^4.6.5
  get_it: ^7.3.0
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  dio: ^5.1.1
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.4
  shared_preferences: ^2.1.0
  video_player: ^2.6.1
  just_audio: ^0.9.32
  flutter_sound: ^9.2.13
  pin_code_fields: ^7.4.0
  vibration: ^1.7.6
  permission_handler: ^10.2.0
  wakelock: ^0.6.2
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  flutter_exif_rotation: ^0.5.1
  sizer: ^2.0.15
  auto_size_text: ^3.0.0
  oktoast: ^3.3.1
  loading_indicator: ^3.1.0
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  intl: ^0.18.1
  flutter_dotenv: ^5.0.2

  flutter_colorpicker: ^1.0.3
  flame: 1.7.3
  flame_fire_atlas: 1.3.5
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  flutter_cache_manager: ^3.3.0
  card_swiper: ^2.0.4
  flame_svg: 1.7.3
  image_gallery_saver: ^1.7.1
  syncfusion_flutter_sliders: ^21.2.4
  syncfusion_flutter_core: ^21.2.4
  loading_animation_widget: ^1.2.0+4
  percent_indicator: ^4.2.3
  video_thumbnail: ^0.5.3
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  animated_page_reveal: ^1.0.0
  http: ^1.1.0
  speech_to_text: ^6.6.0
  badges: ^3.1.2
  provider: ^6.1.2
  flutter_pdfview: ^1.3.4
  flutter_openim_sdk: 3.8.1+2
  hive_flutter: ^1.1.0
  sprintf: ^7.0.0
  crypto: ^3.0.3
  talker_dio_logger: ^4.5.1
  flutter_image_compress: ^2.3.0
  wechat_assets_picker: ^8.7.0
  wechat_camera_picker: ^4.1.2
  emoji_picker_flutter: ^1.6.4
  # video_compress: ^3.1.2
  flutter_tts: ^4.0.2
  universal_html: ^2.0.0
  pinput: ^5.0.1
  timer_count_down: ^2.2.2
  share_plus: ^6.3.4
  webview_flutter: ^4.5.0
  local_captcha: ^1.0.5
  calendar_date_picker2: ^1.0.5
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flame_lint: ^0.2.0+2
  timer_count_down: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/pdfs/
    - assets/backgrounds/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/audios/
    - assets/videos/
    - assets/images/game/
    - assets/voices/
    - assets/.env
    - assets/images/game/coloring/
    # demo
    - assets/videos/other/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
