// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTbq1YuboiqPS33U4ou37NXTuZnqutHdo',
    appId: '1:61674290763:web:dcc504cd2a62d4a97b17ce',
    messagingSenderId: '61674290763',
    projectId: 'appkid-259eb',
    authDomain: 'appkid-259eb.firebaseapp.com',
    storageBucket: 'appkid-259eb.appspot.com',
    measurementId: 'G-Y8GXV1FKBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTbq1YuboiqPS33U4ou37NXTuZnqutHdo',
    appId: '1:61674290763:web:dcc504cd2a62d4a97b17ce',
    messagingSenderId: '61674290763',
    projectId: 'appkid-259eb',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'appkid-259eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbq1YuboiqPS33U4ou37NXTuZnqutHdo',
    appId: '1:61674290763:web:dcc504cd2a62d4a97b17ce',
    messagingSenderId: '61674290763',
    projectId: 'appkid-259eb',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'appkid-259eb.appspot.com',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTbq1YuboiqPS33U4ou37NXTuZnqutHdo',
    appId: '1:61674290763:web:dcc504cd2a62d4a97b17ce',
    messagingSenderId: '61674290763',
    projectId: 'appkid-259eb',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'appkid-259eb.appspot.com',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );
}